# GitHub Dependabot Configuration
#
# Dependabot can maintain your repository’s dependencies automatically.
#
# Documentation:
# - https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference
# - https://docs.github.com/en/code-security/dependabot/dependabot-version-updates
# - https://github.com/dependabot/dependabot-core/#readme

version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    groups:
      github-actions-production:
        dependency-type: production
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore:"
    labels:
      - dependencies
    open-pull-requests-limit: 5
