name: Git Commit Linter

on:
  workflow_call:
    inputs:
      commitlint_cli_version:
        type: string
        required: false
        default: "19.5.0"
        description: Commitlint CLI Version
      commitlint_config_cordada_version:
        type: string
        required: false
        default: "0.1.4"
        description: Version of Commitlint Configuration for Cordada
      vcs_ref_from:
        type: string
        required: false
        default: ${{ github.event.pull_request.base.sha || github.sha }}
        description: VCS Reference Range - From
      vcs_ref_to:
        type: string
        required: false
        default: ${{ github.event.pull_request.head.sha || github.sha }}
        description: VCS Reference Range - To

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04

    env:
      COMMITLINT_CLI_VERSION: ${{ inputs.commitlint_cli_version }}
      COMMITLINT_CONFIG_CORDADA_VERSION: ${{ inputs.commitlint_config_cordada_version }}
      CORDADA_NPM_REGISTRY: https://registry.npmjs.org

    steps:
      - name: Check Out VCS Repository
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Set Up Node.js
        id: set_up_nodejs
        uses: actions/setup-node@v4.3.0
        with:
          node-version: "lts/*"

      - name: Restoring/Saving Cache
        uses: actions/cache@v4.2.3
        with:
          path: node_modules
          key: js-v2-deps-${{ runner.os }}-${{ steps.set_up_nodejs.outputs.node-version }}-${{ env.COMMITLINT_CLI_VERSION }}-${{ env.COMMITLINT_CONFIG_CORDADA_VERSION }}

      - name: Install Dependencies
        run: |
          rm -f package.json package-lock.json

          npm config set @cordada:registry="${CORDADA_NPM_REGISTRY}" --location project

          npm install @commitlint/cli@"${COMMITLINT_CLI_VERSION}"
          npm install @cordada/commitlint-config-cordada@"${COMMITLINT_CONFIG_CORDADA_VERSION}"
        env:
          npm_config_audit: "false"
          npm_config_fund: "false"

      - name: Lint Git Commit Messages
        run: |
          npm exec -- commitlint --from "$VCS_REF_FROM" --to "$VCS_REF_TO"
        env:
          VCS_REF_FROM: ${{ inputs.vcs_ref_from }}
          VCS_REF_TO: ${{ inputs.vcs_ref_to }}
