# GitHub Actions Workflow for Super-Linter
#
# Super-Linter is a simple combination of various linters, written in bash, to help validate your
# source code.
#
# - Web site: https://github.com/super-linter/super-linter/
# - Documentation: https://github.com/super-linter/super-linter#readme

name: Super-Linter

on:
  workflow_call:
    inputs:
      default_git_branch:
        type: string
        required: true
        description: Default Branch of Git Repository
      validate_all_codebase:
        type: boolean
        required: false
        default: true
        description: When `true`, validate all files; when `false`, only new or edited files.
      filter_regex_exclude:
        type: string
        required: false
        description: Regular expression defining which files will be excluded from linting.

      validate_editorconfig:
        type: boolean
        required: false
        default: false
      validate_json_prettier:
        type: boolean
        required: false
        default: false
      validate_markdown:
        type: boolean
        required: false
        default: false
      validate_openapi:
        type: boolean
        required: false
        default: false
      validate_python_black:
        type: boolean
        required: false
        default: false
      validate_python_flake8:
        type: boolean
        required: false
        default: false
      validate_python_isort:
        type: boolean
        required: false
        default: false
      validate_python_mypy:
        type: boolean
        required: false
        default: false
      validate_sql_sqlfluff:
        type: boolean
        required: false
        default: false
      validate_yaml_prettier:
        type: boolean
        required: false
        default: false

      editorconfig_file_name:
        type: string
        required: false
        default: .editorconfig-checker.json
      markdown_config_file:
        type: string
        required: false
        default: .markdownlint.yaml
      python_black_config_file:
        type: string
        required: false
        default: .black.cfg.toml
      python_flake8_config_file:
        type: string
        required: false
        default: .flake8
      python_isort_config_file:
        type: string
        required: false
        default: .isort.cfg
      python_mypy_config_file:
        type: string
        required: false
        default: mypy.ini
      sql_sqlfluff_config_file:
        type: string
        required: false
        default: .sqlfluff

permissions:
  contents: read
  statuses: write
  checks: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04

    steps:
      - name: Check Out VCS Repository
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`.
          fetch-depth: 0

      - name: Configure Super-Linter
        run: |
          for language_var_name in ${LANGUAGE_VAR_NAMES:?}; do
            if [ "${!language_var_name}" == 'true' ]; then
              echo "${language_var_name^^}=true" >> "$GITHUB_ENV"
            fi
          done

          if [ "$validate_editorconfig" == 'true' ]; then
            echo "EDITORCONFIG_FILE_NAME=${{ inputs.editorconfig_file_name }}" >> "$GITHUB_ENV"
          fi

          if [ "$validate_markdown" == 'true' ]; then
            echo "MARKDOWN_CONFIG_FILE=${{ inputs.markdown_config_file }}" >> "$GITHUB_ENV"
          fi

          if [ "$validate_python_black" == 'true' ]; then
            echo "PYTHON_BLACK_CONFIG_FILE=${{ inputs.python_black_config_file }}" >> "$GITHUB_ENV"
          fi

          if [ "$validate_python_flake8" == 'true' ]; then
            echo "PYTHON_FLAKE8_CONFIG_FILE=${{ inputs.python_flake8_config_file }}" >> "$GITHUB_ENV"
          fi

          if [ "$validate_python_isort" == 'true' ]; then
            echo "PYTHON_ISORT_CONFIG_FILE=${{ inputs.python_isort_config_file }}" >> "$GITHUB_ENV"
          fi

          if [ "$validate_python_mypy" == 'true' ]; then
            echo "PYTHON_MYPY_CONFIG_FILE=${{ inputs.python_mypy_config_file }}" >> "$GITHUB_ENV"
          fi

          if [ "$validate_sqlfluff" == 'true' ]; then
            echo "SQLFLUFF_CONFIG_FILE=${{ inputs.sql_sqlfluff_config_file }}" >> "$GITHUB_ENV"
          fi
        env:
          LANGUAGE_VAR_NAMES: >-
            validate_editorconfig
            validate_json_prettier
            validate_markdown
            validate_openapi
            validate_python_black
            validate_python_flake8
            validate_python_isort
            validate_python_mypy
            validate_sqlfluff
            validate_yaml_prettier
          validate_editorconfig: ${{ inputs.validate_editorconfig }}
          validate_json_prettier: ${{ inputs.validate_json_prettier }}
          validate_markdown: ${{ inputs.validate_markdown }}
          validate_openapi: ${{ inputs.validate_openapi }}
          validate_python_black: ${{ inputs.validate_python_black }}
          validate_python_flake8: ${{ inputs.validate_python_flake8 }}
          validate_python_isort: ${{ inputs.validate_python_isort }}
          validate_python_mypy: ${{ inputs.validate_python_mypy }}
          validate_sqlfluff: ${{ inputs.validate_sql_sqlfluff }}
          validate_yaml_prettier: ${{ inputs.validate_yaml_prettier }}

      - name: Lint
        uses: super-linter/super-linter/slim@v7.3.0
        env:
          DEFAULT_BRANCH: ${{ inputs.default_git_branch }}
          LINTER_RULES_PATH: /
          VALIDATE_ALL_CODEBASE: ${{ inputs.validate_all_codebase }}
          FILTER_REGEX_EXCLUDE: ${{ inputs.filter_regex_exclude }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
